/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArcadeDetail: typeof import('./src/components/ArcadeDetail.vue')['default']
    ArcadeList: typeof import('./src/components/ArcadeList.vue')['default']
    Busuanzi: typeof import('./src/components/busuanzi.vue')['default']
    copy: typeof import('./src/components/DetailCard copy.vue')['default']
    DetailCard: typeof import('./src/components/DetailCard.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NFlex: typeof import('naive-ui')['NFlex']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTable: typeof import('naive-ui')['NTable']
    NThing: typeof import('naive-ui')['NThing']
    ReigonNotify: typeof import('./src/components/ReigonNotify.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectRegion: typeof import('./src/components/SelectRegion.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UpdateForm: typeof import('./src/components/UpdateForm.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCounter: typeof import('@varlet/ui')['_CounterComponent']
    VarOption: typeof import('@varlet/ui')['_OptionComponent']
    VarSelect: typeof import('@varlet/ui')['_SelectComponent']
    VarSnackbar: typeof import('@varlet/ui')['_SnackbarComponent']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
